services:
  - docker
language: python
python:
  - "2.7"
script:
  - python -m pytest -v
branches:
  only:
    - master
before_install:
  - docker build -t lioneleoy/traviscibuildtest .
script:
  - docker images lioneleoy/traviscibuildtest
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push lioneleoy/traviscibuildtest;
    fi